services:
    postgres:
        image: postgres:15.3
        container_name: my-postgres
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_USER: postgres
            POSTGRES_DB: mydatabase
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - app-network

    backend:
        build:
            context: ./backend
            dockerfile: src/main/docker/Dockerfile.jvm
        container_name: my-backend
        environment:
            QUARKUS_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
            QUARKUS_DATASOURCE_USERNAME: postgres
            QUARKUS_DATASOURCE_PASSWORD: mysecretpassword
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: my-frontend
        ports:
            - "4200:80"
        depends_on:
            - backend
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
